add color to p tag to clearly see comment in pull request page and
bhumijgupta/Github-vanced pull request #9
Opened 2019-10-23 17:57 UTC by MERWINDASARI

changed  checkStatus fun name since it is already redefined

2019-10-27 06:12 UTC, bhumijgupta requested changes

2019-10-27 06:12 UTC, bhumijgupta commented on darktheme.js
> +const checkStatus_ = () => {
Can you provide the motive to change the name of the function?

2019-10-27 08:40 UTC, MERWINDASARI commented on darktheme.js
> +const checkStatus_ = () => {
![github_vanced_error](https://user-images.githubusercontent.com/35071428/67631992-85495e80-f8c3-11e9-93af-e30033559b3a.PNG)

because of this error

2019-10-31 03:45 UTC, bhumijgupta approved these changes

2019-10-31 03:45 UTC, bhumijgupta commented
LGTM! Thanks for opening a Pull Request!

2019-10-31 03:45 UTC, merged